name: flutter_application_1
description: "Application pour recevoir les donnÃ©es des capteurs RPi via MQTT"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.0.0
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.2
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true